//go:build integration

package privacyrequests

// relationalUserReferenceInventory is the reviewed #245 disposition for every
// FK column that currently targets users(id). Integration coverage compares
// this closed manifest with information_schema so a new relationship cannot
// silently inherit an erasure treatment. The issue's older count was 65; the
// current baseline has 85 constraints (69 textual REFERENCES occurrences).
var relationalUserReferenceInventory = map[string]string{
	"activity_connections.user_id":                               "DELETE_ACTIVITY",
	"announcement_audit_events.actor_user_id":                    "ANONYMIZE_AUDIT_PRINCIPAL",
	"announcement_deliveries.user_id":                            "DELETE_DELIVERY",
	"announcements.author_id":                                    "KEEP_OPAQUE_ACTOR",
	"announcements.expired_by_id":                                "KEEP_OPAQUE_ACTOR",
	"announcements.published_by_id":                              "KEEP_OPAQUE_ACTOR",
	"competition_categories.approved_by_user_id":                 "KEEP_OPAQUE_ACTOR",
	"competition_documents.author_id":                            "KEEP_OPAQUE_ACTOR",
	"consent_forms.granted_by_user_id":                           "KEEP_OPAQUE_ACTOR",
	"consent_forms.user_id":                                      "RESTRICT_CONSENT",
	"data_erasure_requests.claimed_by":                           "RESTRICT_PRIVACY_CONTROL",
	"data_erasure_requests.decided_by":                           "RESTRICT_PRIVACY_CONTROL",
	"data_erasure_requests.identity_verified_by":                 "RESTRICT_PRIVACY_CONTROL",
	"data_erasure_requests.representation_guardian_id":           "RESTRICT_PRIVACY_CONTROL",
	"data_erasure_requests.representation_verified_by":           "RESTRICT_PRIVACY_CONTROL",
	"data_erasure_requests.requester_user_id":                    "RESTRICT_PRIVACY_CONTROL",
	"data_erasure_requests.subject_user_id":                      "RESTRICT_PRIVACY_CONTROL",
	"email_outbox.privacy_requester_id":                          "KEEP_OPAQUE_ACTOR",
	"email_verification_tokens.user_id":                          "DELETE_AUTH",
	"equipment_audit_events.actor_user_id":                       "ANONYMIZE_AUDIT_PRINCIPAL",
	"event_responses.checked_in_by_id":                           "KEEP_OPAQUE_ACTOR",
	"event_responses.responded_by_id":                            "KEEP_OPAQUE_ACTOR",
	"event_responses.user_id":                                    "DELETE_PARTICIPATION",
	"events.cancelled_by_id":                                     "KEEP_OPAQUE_ACTOR",
	"events.created_by_id":                                       "KEEP_OPAQUE_ACTOR",
	"feature_flag_events.actor_user_id":                          "ANONYMIZE_AUDIT_PRINCIPAL",
	"feature_flags.updated_by_id":                                "KEEP_OPAQUE_ACTOR",
	"maintenance_tasks.created_by_id":                            "KEEP_OPAQUE_ACTOR",
	"member_profile_audit_events.actor_user_id":                  "ANONYMIZE_AUDIT_PRINCIPAL",
	"member_profile_audit_events.subject_user_id":                "ANONYMIZE_AUDIT_PRINCIPAL",
	"member_profiles.user_id":                                    "DELETE_PROFILE",
	"minor_credential_audit.actor_user_id":                       "ANONYMIZE_AUDIT_PRINCIPAL",
	"minor_credential_audit.guardian_user_id":                    "ANONYMIZE_AUDIT_PRINCIPAL",
	"minor_credential_audit.minor_user_id":                       "ANONYMIZE_AUDIT_PRINCIPAL",
	"password_reset_tokens.user_id":                              "DELETE_AUTH",
	"performance_metrics.user_id":                                "DELETE_TRAINING_RESULT",
	"photo_album_audit_events.actor_user_id":                     "ANONYMIZE_AUDIT_PRINCIPAL",
	"photo_albums.archived_by_id":                                "KEEP_OPAQUE_ACTOR",
	"photo_albums.created_by_id":                                 "KEEP_OPAQUE_ACTOR",
	"privacy_executor_grants.granted_by":                         "RESTRICT_PRIVACY_CONTROL",
	"privacy_executor_grants.revoked_by":                         "RESTRICT_PRIVACY_CONTROL",
	"privacy_executor_grants.user_id":                            "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_activation.updated_by":                      "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_dependant_resolutions.dependant_id":         "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_dependant_resolutions.guardian_id_snapshot": "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_dependant_resolutions.verified_by":          "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_policies.adopted_by":                        "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_retention_exceptions.actor_ref":             "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_retention_exceptions.owner_ref":             "RESTRICT_PRIVACY_CONTROL",
	"privacy_reviewer_grants.granted_by":                         "RESTRICT_PRIVACY_CONTROL",
	"privacy_reviewer_grants.revoked_by":                         "RESTRICT_PRIVACY_CONTROL",
	"privacy_reviewer_grants.user_id":                            "RESTRICT_PRIVACY_CONTROL",
	"repair_requests.reported_by_id":                             "ANONYMIZE_REPORTER",
	"sessions.user_id":                                           "DELETE_AUTH",
	"staff_grant_audit_events.actor_user_id":                     "ANONYMIZE_AUDIT_PRINCIPAL",
	"staff_grants.granted_by_id":                                 "KEEP_OPAQUE_ACTOR",
	"staff_grants.revoked_by_id":                                 "KEEP_OPAQUE_ACTOR",
	"staff_grants.user_id":                                       "REVOKE_ACCESS",
	"suggestions.requester_id":                                   "DELETE_SUGGESTION",
	"suggestions.responded_by_id":                                "KEEP_OPAQUE_ACTOR",
	"synced_activities.user_id":                                  "DELETE_ACTIVITY",
	"training_copy_events.copied_by_id":                          "ANONYMIZE_AUDIT_PRINCIPAL",
	"training_cycle_competition_targets.added_by_id":             "KEEP_OPAQUE_ACTOR",
	"training_cycles.created_by_id":                              "KEEP_OPAQUE_ACTOR",
	"training_cycles.updated_by_id":                              "KEEP_OPAQUE_ACTOR",
	"training_group_members.added_by_id":                         "KEEP_OPAQUE_ACTOR",
	"training_groups.created_by_id":                              "KEEP_OPAQUE_ACTOR",
	"training_logs.user_id":                                      "DELETE_TRAINING_RESULT",
	"training_plan_publications.published_by_id":                 "KEEP_OPAQUE_ACTOR",
	"training_plans.created_by_id":                               "KEEP_OPAQUE_ACTOR",
	"training_prescriptions.athlete_user_id":                     "DELETE_PRESCRIPTION",
	"training_routines.owner_user_id":                            "KEEP_OPAQUE_ACTOR",
	"training_session_activity_matches.decided_by_user_id":       "KEEP_OPAQUE_ACTOR",
	"training_session_activity_matches.user_id":                  "DELETE_ACTIVITY",
	"training_session_outcomes.user_id":                          "DELETE_TRAINING_RESULT",
	"training_sessions.cancelled_by_id":                          "KEEP_OPAQUE_ACTOR",
	"training_sessions.created_by_id":                            "KEEP_OPAQUE_ACTOR",
	"training_variation_group_members.added_by_id":               "KEEP_OPAQUE_ACTOR",
	"training_variation_groups.created_by_id":                    "KEEP_OPAQUE_ACTOR",
	"training_variations.created_by_id":                          "KEEP_OPAQUE_ACTOR",
	"training_variations.retired_by_id":                          "KEEP_OPAQUE_ACTOR",
	"user_memberships.user_id":                                   "ANONYMIZE_MEMBERSHIP_PRINCIPAL",
	"user_platform_roles.user_id":                                "DELETE_AUTH",
	"users.guardian_id":                                          "DELETE_RELATIONSHIP",
	"water_intensity_profiles.created_by_id":                     "KEEP_OPAQUE_ACTOR",
}

// Indirect columns are not discoverable from FK metadata and therefore need
// explicit canaries. Subject-owned rows are deleted by their category; the
// remaining snapshots retain only an opaque actor UUID after IDENTITY_CLEAR.
var relationalIndirectInventory = map[string]string{
	"equipment_audit_events.before_state":       "ANONYMIZE_SUBJECT_CANARIES_KEEP_EQUIPMENT",
	"equipment_audit_events.after_state":        "ANONYMIZE_SUBJECT_CANARIES_KEEP_EQUIPMENT",
	"minor_credential_audit.issued_login_id":    "ANONYMIZE_SUBJECT_LOGIN",
	"staff_grant_audit_events.reason":           "ANONYMIZE_SUBJECT_CANARIES",
	"synced_activities.provider_metrics":        "DELETE_ACTIVITY",
	"synced_activities.raw_summary":             "DELETE_ACTIVITY",
	"training_prescriptions.snapshot":           "DELETE_PRESCRIPTION",
	"training_routines.snapshot":                "KEEP_WORKOUT_ONLY",
	"training_variations.change_summary":        "ANONYMIZE_MEMBERSHIP_CANARIES",
	"training_variations.patch":                 "ANONYMIZE_MEMBERSHIP_CANARIES",
	"training_logs.notes":                       "DELETE_TRAINING_RESULT",
	"training_session_outcomes.perception_note": "DELETE_TRAINING_RESULT",
	"data_erasure_requests.policy_snapshot":     "RESTRICT_PRIVACY_CONTROL",
	"privacy_request_execution_plans.plan":      "RESTRICT_PRIVACY_CONTROL",
}
