DO $$ BEGIN CREATE TYPE training_routine_kind AS ENUM ('BLOCK', 'SEGMENT', 'SESSION'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE training_routine_visibility AS ENUM ('PRIVATE', 'SHARED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS training_routines (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(180) NOT NULL, description varchar(1000) NOT NULL DEFAULT '',
 kind training_routine_kind NOT NULL, visibility training_routine_visibility NOT NULL DEFAULT 'PRIVATE',
 owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 programme_id uuid NULL REFERENCES programmes(id) ON DELETE RESTRICT, team_id uuid NULL REFERENCES teams(id) ON DELETE RESTRICT,
 modality training_segment_modality NULL, objective training_objective NULL, method varchar(80) NOT NULL DEFAULT '', tags text[] NOT NULL DEFAULT '{}',
 source_id uuid NOT NULL, source_updated_at timestamptz NOT NULL, snapshot jsonb NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT training_routines_name_valid CHECK (name = btrim(name) AND char_length(name) BETWEEN 2 AND 180),
 CONSTRAINT training_routines_description_valid CHECK (description = btrim(description) AND char_length(description) <= 1000),
 CONSTRAINT training_routines_method_valid CHECK (method = btrim(method) AND char_length(method) <= 80),
 CONSTRAINT training_routines_tags_valid CHECK (cardinality(tags) <= 20 AND array_position(tags, NULL) IS NULL AND char_length(array_to_string(tags, ',')) <= 800),
 CONSTRAINT training_routines_snapshot_valid CHECK (jsonb_typeof(snapshot) = 'object'),
 CONSTRAINT training_routines_scope_valid CHECK ((visibility = 'PRIVATE' AND programme_id IS NULL AND team_id IS NULL) OR (visibility = 'SHARED' AND num_nonnulls(programme_id, team_id) = 1))
);
CREATE INDEX IF NOT EXISTS training_routines_owner_idx ON training_routines (owner_user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS training_routines_programme_idx ON training_routines (programme_id, updated_at DESC) WHERE programme_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS training_routines_team_idx ON training_routines (team_id, updated_at DESC) WHERE team_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS training_routines_tags_idx ON training_routines USING gin (tags);

CREATE TABLE IF NOT EXISTS training_copy_events (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_kind varchar(20) NOT NULL CHECK (source_kind IN ('BLOCK', 'SEGMENT', 'SESSION', 'DAY', 'WEEK', 'ROUTINE')),
 source_id uuid NOT NULL, source_updated_at timestamptz NOT NULL,
 destination_kind varchar(20) NOT NULL CHECK (destination_kind IN ('BLOCK', 'SEGMENT', 'SESSION', 'WEEK')),
 destination_id uuid NOT NULL, copied_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, copied_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS training_copy_events_destination_idx ON training_copy_events (destination_kind, destination_id);
CREATE INDEX IF NOT EXISTS training_copy_events_source_idx ON training_copy_events (source_kind, source_id);

CREATE OR REPLACE FUNCTION prevent_training_copy_event_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'training copy events are append-only';
END;
$$;

DROP TRIGGER IF EXISTS training_copy_events_immutable_trigger ON training_copy_events;
CREATE TRIGGER training_copy_events_immutable_trigger
    BEFORE UPDATE OR DELETE ON training_copy_events
    FOR EACH ROW EXECUTE FUNCTION prevent_training_copy_event_mutation();

CREATE OR REPLACE FUNCTION training_block_snapshot(p_block_id uuid) RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT jsonb_strip_nulls(jsonb_build_object('purpose', block.purpose::text, 'title', block.title, 'instructions', block.instructions, 'gym', CASE WHEN gym.block_id IS NULL THEN NULL ELSE jsonb_build_object('structure', gym.structure::text, 'objective', gym.objective::text, 'rounds', gym.rounds, 'round_recovery_seconds', gym.round_recovery_seconds, 'exercises', COALESCE((SELECT jsonb_agg(jsonb_strip_nulls(jsonb_build_object('name', exercise.name, 'sets', exercise.sets, 'repetitions', exercise.repetitions, 'duration_seconds', exercise.duration_seconds, 'distance_metres', exercise.distance_metres, 'recovery_seconds', exercise.recovery_seconds, 'resistance_kind', exercise.resistance_kind::text, 'resistance_value', exercise.resistance_value, 'resistance_text', exercise.resistance_text, 'execution_intent', exercise.execution_intent::text, 'tempo', exercise.tempo, 'notes', exercise.notes)) ORDER BY exercise.position) FROM gym_exercises exercise WHERE exercise.block_id = gym.block_id), '[]'::jsonb)) END)) FROM training_segment_blocks block LEFT JOIN gym_block_prescriptions gym ON gym.block_id = block.id WHERE block.id = p_block_id $$;
CREATE OR REPLACE FUNCTION training_segment_snapshot(p_segment_id uuid) RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT jsonb_strip_nulls(jsonb_build_object('modality', segment.modality::text, 'title', segment.title, 'location', segment.location, 'planned_duration_minutes', segment.planned_duration_minutes, 'planned_start_offset_minutes', segment.planned_start_offset_minutes, 'transition_duration_minutes', segment.transition_duration_minutes, 'equipment_notes', segment.equipment_notes, 'blocks', COALESCE((SELECT jsonb_agg(training_block_snapshot(block.id) ORDER BY block.position) FROM training_segment_blocks block WHERE block.segment_id = segment.id), '[]'::jsonb))) FROM training_session_segments segment WHERE segment.id = p_segment_id $$;
CREATE OR REPLACE FUNCTION training_session_snapshot(p_session_id uuid) RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT jsonb_build_object('title', session.title, 'description', session.description, 'entry_kind', session.entry_kind::text, 'duration_seconds', extract(epoch FROM session.ends_at - session.starts_at)::integer, 'segments', COALESCE((SELECT jsonb_agg(training_segment_snapshot(segment.id) ORDER BY segment.position) FROM training_session_segments segment WHERE segment.session_id = session.id), '[]'::jsonb)) FROM training_sessions session WHERE session.id = p_session_id AND session.status = 'ACTIVE' $$;
CREATE OR REPLACE FUNCTION restore_training_block(p_snapshot jsonb, p_segment_id uuid) RETURNS uuid LANGUAGE plpgsql AS $$ DECLARE new_block_id uuid; gym jsonb; exercise jsonb; BEGIN gym := p_snapshot->'gym'; IF NOT EXISTS (SELECT 1 FROM training_session_segments segment JOIN training_sessions session ON session.id = segment.session_id WHERE segment.id = p_segment_id AND session.status = 'ACTIVE') THEN RAISE NO_DATA_FOUND; END IF; IF gym IS NOT NULL AND jsonb_typeof(gym) = 'object' AND NOT EXISTS (SELECT 1 FROM training_session_segments WHERE id = p_segment_id AND modality = 'GYM') THEN RAISE CHECK_VIOLATION USING MESSAGE = 'structured gym blocks require a gym segment'; END IF; INSERT INTO training_segment_blocks (segment_id, position, purpose, title, instructions) SELECT p_segment_id, COALESCE(max(position), 0) + 1, (p_snapshot->>'purpose')::training_block_purpose, COALESCE(p_snapshot->>'title', ''), p_snapshot->>'instructions' FROM training_segment_blocks WHERE segment_id = p_segment_id RETURNING id INTO new_block_id; IF gym IS NOT NULL AND jsonb_typeof(gym) = 'object' THEN INSERT INTO gym_block_prescriptions (block_id, structure, objective, rounds, round_recovery_seconds) VALUES (new_block_id, (gym->>'structure')::gym_block_structure, (gym->>'objective')::training_objective, (gym->>'rounds')::integer, NULLIF(gym->>'round_recovery_seconds', '')::integer); FOR exercise IN SELECT value FROM jsonb_array_elements(COALESCE(gym->'exercises', '[]'::jsonb)) LOOP INSERT INTO gym_exercises (block_id, position, name, sets, repetitions, duration_seconds, distance_metres, recovery_seconds, resistance_kind, resistance_value, resistance_text, execution_intent, tempo, notes) SELECT new_block_id, COALESCE(max(position), 0) + 1, exercise->>'name', NULLIF(exercise->>'sets', '')::integer, NULLIF(exercise->>'repetitions', '')::integer, NULLIF(exercise->>'duration_seconds', '')::integer, NULLIF(exercise->>'distance_metres', '')::integer, NULLIF(exercise->>'recovery_seconds', '')::integer, NULLIF(exercise->>'resistance_kind', '')::gym_resistance_kind, NULLIF(exercise->>'resistance_value', '')::double precision, NULLIF(exercise->>'resistance_text', ''), NULLIF(exercise->>'execution_intent', '')::gym_execution_intent, NULLIF(exercise->>'tempo', ''), COALESCE(exercise->>'notes', '') FROM gym_exercises WHERE block_id = new_block_id; END LOOP; END IF; RETURN new_block_id; END $$;
CREATE OR REPLACE FUNCTION restore_training_segment(p_snapshot jsonb, p_session_id uuid) RETURNS uuid LANGUAGE plpgsql AS $$ DECLARE new_segment_id uuid; block jsonb; BEGIN IF NOT EXISTS (SELECT 1 FROM training_sessions WHERE id = p_session_id AND status = 'ACTIVE') THEN RAISE NO_DATA_FOUND; END IF; INSERT INTO training_session_segments (session_id, position, modality, title, location, planned_duration_minutes, planned_start_offset_minutes, transition_duration_minutes, equipment_notes) SELECT p_session_id, COALESCE(max(position), 0) + 1, (p_snapshot->>'modality')::training_segment_modality, COALESCE(p_snapshot->>'title', ''), COALESCE(p_snapshot->>'location', ''), NULLIF(p_snapshot->>'planned_duration_minutes', '')::integer, NULLIF(p_snapshot->>'planned_start_offset_minutes', '')::integer, NULLIF(p_snapshot->>'transition_duration_minutes', '')::integer, COALESCE(p_snapshot->>'equipment_notes', '') FROM training_session_segments WHERE session_id = p_session_id RETURNING id INTO new_segment_id; FOR block IN SELECT value FROM jsonb_array_elements(COALESCE(p_snapshot->'blocks', '[]'::jsonb)) LOOP PERFORM restore_training_block(block, new_segment_id); END LOOP; RETURN new_segment_id; END $$;
CREATE OR REPLACE FUNCTION restore_training_session(p_snapshot jsonb, p_plan_id uuid, p_starts_at timestamptz, p_created_by_id uuid) RETURNS uuid LANGUAGE plpgsql AS $$ DECLARE new_session_id uuid; segment jsonb; BEGIN INSERT INTO training_sessions (plan_id, title, description, starts_at, ends_at, entry_kind, created_by_id) SELECT plan.id, p_snapshot->>'title', COALESCE(p_snapshot->>'description', ''), p_starts_at, p_starts_at + ((p_snapshot->>'duration_seconds')::integer * interval '1 second'), (p_snapshot->>'entry_kind')::training_entry_kind, p_created_by_id FROM training_plans plan WHERE plan.id = p_plan_id AND plan.training_group_id IS NOT NULL AND p_starts_at >= (plan.week_start::timestamp AT TIME ZONE 'Europe/Lisbon') AND p_starts_at + ((p_snapshot->>'duration_seconds')::integer * interval '1 second') <= ((plan.week_start + 7)::timestamp AT TIME ZONE 'Europe/Lisbon') RETURNING id INTO new_session_id; IF new_session_id IS NULL THEN RAISE NO_DATA_FOUND; END IF; FOR segment IN SELECT value FROM jsonb_array_elements(COALESCE(p_snapshot->'segments', '[]'::jsonb)) LOOP PERFORM restore_training_segment(segment, new_session_id); END LOOP; RETURN new_session_id; END $$;
