-- Reset-only baseline schema. Apply this file with psql to a newly created database.
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE repair_status AS ENUM ('Pendente', 'Em_Analise', 'Resolvido');
CREATE TYPE consent_type AS ENUM ('Termos_Gerais', 'Uso_Imagem', 'Responsabilidade_Menor');
CREATE TYPE equipment_type AS ENUM ('Boat', 'Paddle', 'Vehicle');
CREATE TYPE equipment_status AS ENUM ('Operational', 'Maintenance', 'Retired');
CREATE TYPE maintenance_status AS ENUM ('Scheduled', 'In_Progress', 'Completed', 'Cancelled');
CREATE TYPE metric_type AS ENUM ('Distance_Metres', 'Duration_Seconds', 'Sessions', 'Custom');
CREATE TYPE medical_declaration AS ENUM ('UNKNOWN', 'NONE_KNOWN', 'PROVIDED');

CREATE TABLE users (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(120) NOT NULL, email citext NULL, email_verified_at timestamptz NULL, minor_login_id citext NULL, password_hash text NULL, credential_version bigint NOT NULL DEFAULT 1, guardian_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, is_dependent boolean NOT NULL DEFAULT false, date_of_birth date NOT NULL, is_active boolean NOT NULL DEFAULT true, leaderboard_visible boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT users_name_valid CHECK (name = btrim(name) AND char_length(name) BETWEEN 2 AND 120), CONSTRAINT users_guardian_not_self CHECK (guardian_id IS NULL OR guardian_id <> id),
 CONSTRAINT users_credential_version_valid CHECK (credential_version > 0),
 CONSTRAINT users_identity_shape CHECK ((is_dependent AND guardian_id IS NOT NULL AND email IS NULL AND ((minor_login_id IS NULL AND password_hash IS NULL) OR (minor_login_id IS NOT NULL AND password_hash IS NOT NULL))) OR (NOT is_dependent AND guardian_id IS NULL AND email IS NOT NULL AND password_hash IS NOT NULL AND minor_login_id IS NULL))
);
CREATE UNIQUE INDEX users_email_uidx ON users (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX users_minor_login_id_uidx ON users (minor_login_id) WHERE minor_login_id IS NOT NULL;
CREATE INDEX users_guardian_id_idx ON users (guardian_id) WHERE guardian_id IS NOT NULL;
CREATE INDEX users_active_idx ON users (is_active);
CREATE TABLE email_verification_tokens (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, email citext NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT email_verification_tokens_expiry_valid CHECK (expires_at > created_at),
 CONSTRAINT email_verification_tokens_consumption_valid CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE UNIQUE INDEX email_verification_tokens_active_user_uidx ON email_verification_tokens (user_id) WHERE consumed_at IS NULL;
CREATE INDEX email_verification_tokens_expiry_idx ON email_verification_tokens (expires_at) WHERE consumed_at IS NULL;
CREATE TABLE password_reset_tokens (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, email citext NOT NULL, token_digest bytea NOT NULL UNIQUE, expires_at timestamptz NOT NULL, consumed_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT password_reset_tokens_digest_valid CHECK (octet_length(token_digest) = 32),
 CONSTRAINT password_reset_tokens_expiry_valid CHECK (expires_at > created_at),
 CONSTRAINT password_reset_tokens_consumption_valid CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
CREATE UNIQUE INDEX password_reset_tokens_active_user_uidx ON password_reset_tokens (user_id) WHERE consumed_at IS NULL;
CREATE INDEX password_reset_tokens_expiry_idx ON password_reset_tokens (expires_at) WHERE consumed_at IS NULL;
CREATE TABLE email_outbox (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), message_type varchar(30) NOT NULL DEFAULT 'EMAIL_VERIFICATION', verification_token_id uuid NULL REFERENCES email_verification_tokens(id) ON DELETE CASCADE, password_reset_token_id uuid NULL REFERENCES password_reset_tokens(id) ON DELETE CASCADE, sealed_payload bytea NULL, status varchar(20) NOT NULL DEFAULT 'PENDING', attempts integer NOT NULL DEFAULT 0, next_attempt_at timestamptz NOT NULL DEFAULT now(), claimed_at timestamptz NULL, sent_at timestamptz NULL, last_error varchar(500) NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT email_outbox_message_valid CHECK ((message_type = 'EMAIL_VERIFICATION' AND verification_token_id IS NOT NULL AND password_reset_token_id IS NULL AND sealed_payload IS NULL) OR (message_type = 'PASSWORD_RESET' AND verification_token_id IS NULL AND password_reset_token_id IS NOT NULL AND sealed_payload IS NOT NULL)),
 CONSTRAINT email_outbox_status_valid CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED', 'CANCELLED')),
 CONSTRAINT email_outbox_attempts_valid CHECK (attempts >= 0),
 CONSTRAINT email_outbox_lifecycle_valid CHECK ((status = 'PENDING' AND claimed_at IS NULL AND sent_at IS NULL) OR (status = 'SENDING' AND claimed_at IS NOT NULL AND sent_at IS NULL) OR (status = 'SENT' AND claimed_at IS NULL AND sent_at IS NOT NULL) OR (status IN ('FAILED', 'CANCELLED') AND claimed_at IS NULL AND sent_at IS NULL))
);
CREATE UNIQUE INDEX email_outbox_verification_token_uidx ON email_outbox (verification_token_id) WHERE verification_token_id IS NOT NULL;
CREATE UNIQUE INDEX email_outbox_password_reset_token_uidx ON email_outbox (password_reset_token_id) WHERE password_reset_token_id IS NOT NULL;
CREATE INDEX email_outbox_delivery_idx ON email_outbox (next_attempt_at, created_at) WHERE status = 'PENDING';
CREATE FUNCTION issue_email_verification(p_user_id uuid, p_email citext, p_created_at timestamptz, p_expires_at timestamptz, p_throttle boolean) RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE issued_id uuid;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));
 IF p_throttle AND EXISTS (SELECT 1 FROM email_verification_tokens WHERE user_id = p_user_id AND created_at > p_created_at - interval '1 minute') THEN
  RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'email_verification_too_soon';
 END IF;
 UPDATE email_outbox SET status = 'CANCELLED', claimed_at = NULL, updated_at = p_created_at WHERE verification_token_id IN (SELECT id FROM email_verification_tokens WHERE user_id = p_user_id AND consumed_at IS NULL) AND status IN ('PENDING', 'SENDING');
 UPDATE email_verification_tokens SET consumed_at = GREATEST(p_created_at, created_at) WHERE user_id = p_user_id AND consumed_at IS NULL;
 INSERT INTO email_verification_tokens (user_id, email, expires_at, created_at) VALUES (p_user_id, p_email, p_expires_at, p_created_at) RETURNING id INTO issued_id;
 INSERT INTO email_outbox (verification_token_id, next_attempt_at, created_at, updated_at) VALUES (issued_id, p_created_at, p_created_at, p_created_at);
 RETURN issued_id;
END;
$$;
CREATE FUNCTION issue_password_reset(p_user_id uuid, p_email citext, p_token_digest bytea, p_sealed_payload bytea, p_created_at timestamptz, p_expires_at timestamptz, p_throttle boolean) RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE issued_id uuid;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended('password-reset:' || p_user_id::text, 0));
 IF NOT EXISTS (SELECT 1 FROM users WHERE id = p_user_id AND email = p_email AND is_active = true AND is_dependent = false) THEN
  RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'password_reset_ineligible';
 END IF;
 IF p_throttle AND EXISTS (SELECT 1 FROM password_reset_tokens WHERE user_id = p_user_id AND created_at > p_created_at - interval '1 minute') THEN
  RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'password_reset_too_soon';
 END IF;
 IF (SELECT count(*) FROM password_reset_tokens WHERE user_id = p_user_id AND created_at > p_created_at - interval '1 hour') >= 5 THEN
  RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'password_reset_limit_exceeded';
 END IF;
 UPDATE email_outbox SET status = 'CANCELLED', claimed_at = NULL, updated_at = p_created_at WHERE password_reset_token_id IN (SELECT id FROM password_reset_tokens WHERE user_id = p_user_id AND consumed_at IS NULL) AND status IN ('PENDING', 'SENDING');
 UPDATE password_reset_tokens SET consumed_at = GREATEST(p_created_at, created_at) WHERE user_id = p_user_id AND consumed_at IS NULL;
 INSERT INTO password_reset_tokens (user_id, email, token_digest, expires_at, created_at) VALUES (p_user_id, p_email, p_token_digest, p_expires_at, p_created_at) RETURNING id INTO issued_id;
 INSERT INTO email_outbox (message_type, password_reset_token_id, sealed_payload, next_attempt_at, created_at, updated_at) VALUES ('PASSWORD_RESET', issued_id, p_sealed_payload, p_created_at, p_created_at, p_created_at);
 RETURN issued_id;
END;
$$;
CREATE TABLE minor_credential_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), minor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, guardian_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, action varchar(20) NOT NULL CHECK (action IN ('ISSUED', 'RECOVERED')), issued_login_id citext NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX minor_credential_audit_minor_created_idx ON minor_credential_audit (minor_user_id, created_at DESC);
CREATE TABLE platform_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(40) NOT NULL UNIQUE, name_pt varchar(120) NOT NULL, CONSTRAINT platform_roles_code_valid CHECK (code = btrim(code) AND code ~ '^[A-Z][A-Z0-9_]*$'), CONSTRAINT platform_roles_name_valid CHECK (name_pt = btrim(name_pt) AND char_length(name_pt) BETWEEN 2 AND 120));
INSERT INTO platform_roles (code, name_pt) VALUES ('ADMIN', 'Administração'), ('STAFF', 'Equipa do clube');
CREATE TABLE user_platform_roles (user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id uuid NOT NULL REFERENCES platform_roles(id) ON DELETE RESTRICT, granted_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (user_id, role_id));
CREATE INDEX user_platform_roles_role_idx ON user_platform_roles (role_id, user_id);
CREATE TABLE equipment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), asset_tag varchar(40) NOT NULL UNIQUE, name varchar(120) NOT NULL, type equipment_type NOT NULL, status equipment_status NOT NULL DEFAULT 'Operational', notes text NOT NULL DEFAULT '', image_object_key varchar(512) NULL, image_content_type varchar(100) NULL, image_size_bytes bigint NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT equipment_asset_tag_valid CHECK (asset_tag = btrim(asset_tag) AND char_length(asset_tag) BETWEEN 2 AND 40), CONSTRAINT equipment_name_valid CHECK (name = btrim(name) AND char_length(name) BETWEEN 2 AND 120), CONSTRAINT equipment_notes_valid CHECK (char_length(notes) <= 4000), CONSTRAINT equipment_image_metadata_complete CHECK ((image_object_key IS NULL AND image_content_type IS NULL AND image_size_bytes IS NULL) OR (image_object_key IS NOT NULL AND image_content_type IS NOT NULL AND image_size_bytes IS NOT NULL)), CONSTRAINT equipment_image_size_valid CHECK (image_size_bytes IS NULL OR image_size_bytes BETWEEN 1 AND 10485760));
CREATE INDEX equipment_status_type_idx ON equipment (status, type);
CREATE TABLE equipment_audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), equipment_id uuid NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT, actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, action varchar(20) NOT NULL CHECK (action IN ('CREATED', 'UPDATED', 'RETIRED', 'REACTIVATED')), before_state jsonb NULL, after_state jsonb NOT NULL, affected_maintenance_ids uuid[] NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX equipment_audit_events_equipment_occurred_idx ON equipment_audit_events (equipment_id, occurred_at DESC, id DESC);
CREATE FUNCTION prevent_equipment_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'equipment audit events are append-only'; END; $$;
CREATE TRIGGER equipment_audit_events_immutable_trigger BEFORE UPDATE OR DELETE ON equipment_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_equipment_audit_mutation();
CREATE TABLE repair_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), idempotency_key uuid NOT NULL UNIQUE, equipment_id uuid NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT, reported_by_id uuid NULL REFERENCES users(id) ON DELETE SET NULL, issue_description varchar(2000) NOT NULL, status repair_status NOT NULL DEFAULT 'Pendente', image_object_key varchar(512) NULL, image_content_type varchar(100) NULL, image_size_bytes bigint NULL, date_reported timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz NULL, CONSTRAINT repair_description_valid CHECK (issue_description = btrim(issue_description) AND char_length(issue_description) BETWEEN 10 AND 2000), CONSTRAINT repair_image_metadata_complete CHECK ((image_object_key IS NULL AND image_content_type IS NULL AND image_size_bytes IS NULL) OR (image_object_key IS NOT NULL AND image_content_type IS NOT NULL AND image_size_bytes IS NOT NULL)), CONSTRAINT repair_image_size_valid CHECK (image_size_bytes IS NULL OR image_size_bytes BETWEEN 1 AND 10485760), CONSTRAINT repair_resolution_valid CHECK ((status = 'Resolvido' AND resolved_at IS NOT NULL) OR (status <> 'Resolvido' AND resolved_at IS NULL)));
CREATE INDEX repair_status_date_idx ON repair_requests (status, date_reported DESC); CREATE INDEX repair_equipment_id_idx ON repair_requests (equipment_id); CREATE INDEX repair_reported_by_id_idx ON repair_requests (reported_by_id);
CREATE TABLE consent_forms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, granted_by_user_id uuid NULL REFERENCES users(id) ON DELETE SET NULL, consent_type consent_type NOT NULL, document_version varchar(40) NOT NULL, document_sha256 char(64) NOT NULL, is_accepted boolean NOT NULL, date_signed timestamptz NOT NULL DEFAULT now(), ip_address inet NULL, user_agent varchar(512) NOT NULL DEFAULT '', CONSTRAINT consent_version_valid CHECK (document_version = btrim(document_version) AND char_length(document_version) BETWEEN 1 AND 40), CONSTRAINT consent_sha256_valid CHECK (document_sha256 ~ '^[0-9a-f]{64}$'), CONSTRAINT consent_accepted_true CHECK (is_accepted), CONSTRAINT consent_user_agent_valid CHECK (char_length(user_agent) <= 512), CONSTRAINT consent_version_unique UNIQUE (user_id, consent_type, document_version));
CREATE INDEX consent_user_type_date_idx ON consent_forms (user_id, consent_type, date_signed DESC);
CREATE TABLE member_profiles (
 user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 phone varchar(32) NOT NULL DEFAULT '', address_line1 varchar(200) NOT NULL DEFAULT '', address_line2 varchar(200) NOT NULL DEFAULT '', postcode varchar(20) NOT NULL DEFAULT '', locality varchar(120) NOT NULL DEFAULT '', country_code varchar(2) NOT NULL DEFAULT '', nationality_code varchar(2) NOT NULL DEFAULT '',
 club_member_number varchar(60) NULL, federation_licence_number varchar(60) NULL,
 emergency_contact_name varchar(120) NOT NULL DEFAULT '', emergency_contact_relationship varchar(80) NOT NULL DEFAULT '', emergency_contact_phone varchar(32) NOT NULL DEFAULT '', emergency_contact_alternate_phone varchar(32) NOT NULL DEFAULT '',
 medical_declaration medical_declaration NOT NULL DEFAULT 'UNKNOWN', allergies varchar(2000) NOT NULL DEFAULT '', medical_conditions varchar(2000) NOT NULL DEFAULT '', medication varchar(2000) NOT NULL DEFAULT '', activity_restrictions varchar(2000) NOT NULL DEFAULT '', medical_notes varchar(2000) NOT NULL DEFAULT '',
 photo_object_key varchar(512) NULL, photo_content_type varchar(100) NULL, photo_size_bytes bigint NULL, photo_consent_form_id uuid NULL REFERENCES consent_forms(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT member_profiles_phone_valid CHECK (phone = '' OR (phone ~ '^[+]?[0-9][0-9 ().-]*[0-9]$' AND char_length(regexp_replace(phone, '[^0-9]', '', 'g')) BETWEEN 7 AND 15)),
 CONSTRAINT member_profiles_emergency_phone_valid CHECK (emergency_contact_phone = '' OR (emergency_contact_phone ~ '^[+]?[0-9][0-9 ().-]*[0-9]$' AND char_length(regexp_replace(emergency_contact_phone, '[^0-9]', '', 'g')) BETWEEN 7 AND 15)),
 CONSTRAINT member_profiles_emergency_alternate_phone_valid CHECK (emergency_contact_alternate_phone = '' OR (emergency_contact_alternate_phone ~ '^[+]?[0-9][0-9 ().-]*[0-9]$' AND char_length(regexp_replace(emergency_contact_alternate_phone, '[^0-9]', '', 'g')) BETWEEN 7 AND 15)),
 CONSTRAINT member_profiles_address_valid CHECK (char_length(address_line1) <= 200 AND char_length(address_line2) <= 200 AND char_length(postcode) <= 20 AND char_length(locality) <= 120),
 CONSTRAINT member_profiles_country_valid CHECK (country_code = '' OR country_code ~ '^[A-Z]{2}$'),
 CONSTRAINT member_profiles_nationality_valid CHECK (nationality_code = '' OR nationality_code ~ '^[A-Z]{2}$'),
 CONSTRAINT member_profiles_emergency_complete CHECK ((emergency_contact_name = '' AND emergency_contact_relationship = '' AND emergency_contact_phone = '' AND emergency_contact_alternate_phone = '') OR (emergency_contact_name <> '' AND emergency_contact_relationship <> '' AND emergency_contact_phone <> '')),
 CONSTRAINT member_profiles_medical_complete CHECK (medical_declaration <> 'PROVIDED' OR allergies <> '' OR medical_conditions <> '' OR medication <> '' OR activity_restrictions <> '' OR medical_notes <> ''),
 CONSTRAINT member_profiles_photo_complete CHECK ((photo_object_key IS NULL AND photo_content_type IS NULL AND photo_size_bytes IS NULL AND photo_consent_form_id IS NULL) OR (photo_object_key IS NOT NULL AND photo_content_type IS NOT NULL AND photo_size_bytes IS NOT NULL AND photo_consent_form_id IS NOT NULL)),
 CONSTRAINT member_profiles_photo_size_valid CHECK (photo_size_bytes IS NULL OR photo_size_bytes BETWEEN 1 AND 10485760)
);
CREATE UNIQUE INDEX member_profiles_club_number_uidx ON member_profiles (club_member_number) WHERE club_member_number IS NOT NULL;
CREATE UNIQUE INDEX member_profiles_federation_number_uidx ON member_profiles (federation_licence_number) WHERE federation_licence_number IS NOT NULL;
CREATE TABLE member_profile_audit_events (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, subject_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 action varchar(40) NOT NULL CHECK (action IN ('SENSITIVE_VIEW', 'PROFILE_UPDATED', 'IDENTITY_UPDATED', 'PHOTO_UPLOADED', 'PHOTO_REPLACED', 'PHOTO_REMOVED')),
 changed_fields text[] NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT member_profile_audit_changed_fields_valid CHECK (array_position(changed_fields, NULL) IS NULL)
);
CREATE INDEX member_profile_audit_subject_occurred_idx ON member_profile_audit_events (subject_user_id, occurred_at DESC, id DESC);
CREATE FUNCTION prevent_member_profile_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'member profile audit events are append-only'; END; $$;
CREATE TRIGGER member_profile_audit_events_immutable_trigger BEFORE UPDATE OR DELETE ON member_profile_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_member_profile_audit_mutation();
CREATE TABLE whatsapp_groups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(120) NOT NULL, discipline varchar(80) NOT NULL, programme_id uuid NULL, url text NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT whatsapp_name_valid CHECK (name = btrim(name) AND char_length(name) BETWEEN 2 AND 120), CONSTRAINT whatsapp_discipline_valid CHECK (discipline = btrim(discipline) AND char_length(discipline) BETWEEN 2 AND 80), CONSTRAINT whatsapp_url_valid CHECK (url LIKE 'https://chat.whatsapp.com/%'), CONSTRAINT whatsapp_group_unique UNIQUE NULLS NOT DISTINCT (name, programme_id));
CREATE INDEX whatsapp_programme_active_idx ON whatsapp_groups (programme_id, is_active);
CREATE TABLE training_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, occurred_at timestamptz NOT NULL, duration_seconds integer NOT NULL, distance_metres integer NOT NULL, notes varchar(2000) NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT training_duration_valid CHECK (duration_seconds BETWEEN 60 AND 86400), CONSTRAINT training_distance_valid CHECK (distance_metres BETWEEN 0 AND 200000), CONSTRAINT training_notes_valid CHECK (char_length(notes) <= 2000));
CREATE INDEX training_user_occurred_idx ON training_logs (user_id, occurred_at DESC);
CREATE TABLE performance_metrics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, metric_type metric_type NOT NULL, label_pt varchar(100) NOT NULL, value numeric(12,2) NOT NULL, unit_pt varchar(30) NOT NULL, measured_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT performance_label_valid CHECK (label_pt = btrim(label_pt) AND char_length(label_pt) BETWEEN 1 AND 100), CONSTRAINT performance_unit_valid CHECK (char_length(unit_pt) <= 30));
CREATE INDEX performance_user_measured_idx ON performance_metrics (user_id, measured_at DESC);
CREATE TABLE news_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title_pt varchar(180) NOT NULL, summary_pt varchar(1000) NOT NULL, url text NULL, published_at timestamptz NOT NULL, is_published boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT news_title_valid CHECK (title_pt = btrim(title_pt) AND char_length(title_pt) BETWEEN 2 AND 180), CONSTRAINT news_summary_valid CHECK (summary_pt = btrim(summary_pt) AND char_length(summary_pt) BETWEEN 2 AND 1000), CONSTRAINT news_url_valid CHECK (url IS NULL OR url ~ '^https://'));
CREATE INDEX news_published_date_idx ON news_items (is_published, published_at DESC);
CREATE TABLE maintenance_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), equipment_id uuid NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT, scheduled_for timestamptz NOT NULL, description varchar(2000) NOT NULL, status maintenance_status NOT NULL DEFAULT 'Scheduled', created_by_id uuid NULL REFERENCES users(id) ON DELETE SET NULL, completed_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT maintenance_description_valid CHECK (description = btrim(description) AND char_length(description) BETWEEN 10 AND 2000), CONSTRAINT maintenance_completion_valid CHECK ((status = 'Completed' AND completed_at IS NOT NULL) OR (status <> 'Completed' AND completed_at IS NULL)));
CREATE INDEX maintenance_status_scheduled_idx ON maintenance_tasks (status, scheduled_for); CREATE INDEX maintenance_equipment_id_idx ON maintenance_tasks (equipment_id);
CREATE TABLE sessions (token text PRIMARY KEY, data bytea NOT NULL, expiry timestamptz NOT NULL); CREATE INDEX sessions_expiry_idx ON sessions (expiry);
CREATE TABLE seasons (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(20) NOT NULL UNIQUE, name varchar(120) NOT NULL, starts_on date NOT NULL, ends_on date NOT NULL, is_current boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT seasons_code_valid CHECK (code = btrim(code) AND char_length(code) BETWEEN 1 AND 20), CONSTRAINT seasons_name_valid CHECK (name = btrim(name) AND char_length(name) BETWEEN 2 AND 120), CONSTRAINT seasons_dates_valid CHECK (starts_on <= ends_on)); CREATE UNIQUE INDEX seasons_current_uidx ON seasons (is_current) WHERE is_current;
CREATE TABLE programmes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(40) NOT NULL UNIQUE, name_pt varchar(120) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT programmes_code_valid CHECK (code = btrim(code) AND code ~ '^[A-Za-z][A-Za-z0-9_]*$'), CONSTRAINT programmes_name_valid CHECK (name_pt = btrim(name_pt) AND char_length(name_pt) BETWEEN 2 AND 120));
INSERT INTO programmes (code, name_pt) VALUES ('Leisure', 'Lazer'), ('Initiation', 'Iniciação'), ('Competition', 'Competição'), ('Kayak_Polo', 'Kayak Polo');
ALTER TABLE whatsapp_groups ADD CONSTRAINT whatsapp_groups_programme_fk FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE RESTRICT;
CREATE TABLE modalities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(20) NOT NULL UNIQUE, name_pt varchar(120) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT modalities_code_valid CHECK (code = btrim(code) AND code ~ '^[A-Z][A-Z0-9]*$'), CONSTRAINT modalities_name_valid CHECK (name_pt = btrim(name_pt) AND char_length(name_pt) BETWEEN 2 AND 120));
INSERT INTO modalities (code, name_pt) VALUES ('K1', 'Caiaque individual'), ('K2', 'Caiaque duplo'), ('K4', 'Caiaque quádruplo'), ('C1', 'Canoa individual'), ('C2', 'Canoa dupla'), ('C4', 'Canoa quádrupla'), ('SUP', 'Stand up paddle');
CREATE TABLE competition_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE RESTRICT, programme_id uuid NOT NULL REFERENCES programmes(id) ON DELETE RESTRICT, code varchar(40) NOT NULL, name_pt varchar(120) NOT NULL, birth_date_from date NULL, birth_date_to date NULL, approved_by_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT competition_categories_code_valid CHECK (code = btrim(code) AND code ~ '^[A-Za-z][A-Za-z0-9_]*$'), CONSTRAINT competition_categories_name_valid CHECK (name_pt = btrim(name_pt) AND char_length(name_pt) BETWEEN 2 AND 120), CONSTRAINT competition_categories_birth_range_valid CHECK (birth_date_from IS NULL OR birth_date_to IS NULL OR birth_date_from <= birth_date_to), CONSTRAINT competition_categories_season_programme_code_unique UNIQUE (season_id, programme_id, code), CONSTRAINT competition_categories_id_season_programme_unique UNIQUE (id, season_id, programme_id));
CREATE TABLE teams (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE RESTRICT, programme_id uuid NOT NULL REFERENCES programmes(id) ON DELETE RESTRICT, code varchar(40) NOT NULL, name varchar(120) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT teams_code_valid CHECK (code = btrim(code) AND code ~ '^[A-Za-z][A-Za-z0-9_]*$'), CONSTRAINT teams_name_valid CHECK (name = btrim(name) AND char_length(name) BETWEEN 2 AND 120), CONSTRAINT teams_season_programme_code_unique UNIQUE (season_id, programme_id, code), CONSTRAINT teams_id_season_programme_unique UNIQUE (id, season_id, programme_id));
CREATE TABLE user_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE RESTRICT, programme_id uuid NOT NULL REFERENCES programmes(id) ON DELETE RESTRICT, team_id uuid NULL, competition_category_id uuid NULL, starts_on date NOT NULL, ends_on date NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT user_memberships_dates_valid CHECK (ends_on IS NULL OR starts_on <= ends_on), CONSTRAINT user_memberships_user_season_programme_unique UNIQUE (user_id, season_id, programme_id), CONSTRAINT user_memberships_team_same_season_programme_fk FOREIGN KEY (team_id, season_id, programme_id) REFERENCES teams(id, season_id, programme_id) ON DELETE RESTRICT, CONSTRAINT user_memberships_category_same_season_programme_fk FOREIGN KEY (competition_category_id, season_id, programme_id) REFERENCES competition_categories(id, season_id, programme_id) ON DELETE RESTRICT);
CREATE INDEX user_memberships_active_user_idx ON user_memberships (user_id, starts_on, ends_on); CREATE INDEX user_memberships_team_idx ON user_memberships (team_id) WHERE team_id IS NOT NULL;
CREATE TABLE membership_modalities (membership_id uuid NOT NULL REFERENCES user_memberships(id) ON DELETE CASCADE, modality_id uuid NOT NULL REFERENCES modalities(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (membership_id, modality_id));
CREATE TYPE event_response_status AS ENUM ('Going', 'NotGoing', 'Waitlisted');
CREATE TABLE events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title varchar(180) NOT NULL, description varchar(4000) NOT NULL DEFAULT '', event_type varchar(20) NOT NULL DEFAULT 'GENERAL', starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, response_deadline timestamptz NULL, capacity integer NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', cancelled_at timestamptz NULL, cancelled_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, cancellation_reason varchar(500) NULL, created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT events_title_valid CHECK (title = btrim(title) AND char_length(title) BETWEEN 2 AND 180), CONSTRAINT events_description_valid CHECK (description = btrim(description) AND char_length(description) <= 4000), CONSTRAINT events_type_valid CHECK (event_type IN ('GENERAL', 'COMPETITION')), CONSTRAINT events_times_valid CHECK (starts_at < ends_at), CONSTRAINT events_deadline_valid CHECK (response_deadline IS NULL OR response_deadline <= starts_at), CONSTRAINT events_capacity_valid CHECK (capacity IS NULL OR capacity > 0), CONSTRAINT events_status_valid CHECK (status IN ('ACTIVE', 'CANCELLED')), CONSTRAINT events_cancellation_reason_valid CHECK (cancellation_reason IS NULL OR (cancellation_reason = btrim(cancellation_reason) AND char_length(cancellation_reason) BETWEEN 2 AND 500)), CONSTRAINT events_cancellation_complete CHECK ((status = 'ACTIVE' AND cancelled_at IS NULL AND cancelled_by_id IS NULL AND cancellation_reason IS NULL) OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND cancelled_by_id IS NOT NULL AND cancellation_reason IS NOT NULL))); CREATE INDEX events_starts_at_idx ON events (starts_at); CREATE INDEX events_status_starts_idx ON events (status, starts_at);
CREATE TABLE event_audiences (event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE, programme_id uuid NOT NULL REFERENCES programmes(id) ON DELETE RESTRICT, PRIMARY KEY (event_id, programme_id)); CREATE INDEX event_audiences_programme_idx ON event_audiences (programme_id, event_id);
CREATE TABLE event_responses (event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, status event_response_status NOT NULL, responded_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, responded_at timestamptz NOT NULL DEFAULT now(), checked_in_at timestamptz NULL, checked_in_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, PRIMARY KEY (event_id, user_id), CONSTRAINT event_responses_checkin_valid CHECK ((checked_in_at IS NULL AND checked_in_by_id IS NULL) OR (checked_in_at IS NOT NULL AND checked_in_by_id IS NOT NULL))); CREATE INDEX event_responses_event_status_idx ON event_responses (event_id, status);
CREATE TABLE training_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title varchar(180) NOT NULL, description varchar(4000) NOT NULL DEFAULT '', programme_id uuid NULL REFERENCES programmes(id) ON DELETE RESTRICT, team_id uuid NULL REFERENCES teams(id) ON DELETE RESTRICT, created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT training_plans_title_valid CHECK (title = btrim(title) AND char_length(title) BETWEEN 2 AND 180), CONSTRAINT training_plans_description_valid CHECK (description = btrim(description) AND char_length(description) <= 4000), CONSTRAINT training_plans_scope_valid CHECK (programme_id IS NOT NULL OR team_id IS NOT NULL)); CREATE INDEX training_plans_programme_idx ON training_plans (programme_id) WHERE programme_id IS NOT NULL; CREATE INDEX training_plans_team_idx ON training_plans (team_id) WHERE team_id IS NOT NULL;
CREATE TABLE training_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE, title varchar(180) NOT NULL, description varchar(4000) NOT NULL DEFAULT '', starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, modality_id uuid NULL REFERENCES modalities(id) ON DELETE RESTRICT, status varchar(20) NOT NULL DEFAULT 'ACTIVE', cancelled_at timestamptz NULL, cancelled_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, cancellation_reason varchar(500) NULL, created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT training_sessions_title_valid CHECK (title = btrim(title) AND char_length(title) BETWEEN 2 AND 180), CONSTRAINT training_sessions_description_valid CHECK (description = btrim(description) AND char_length(description) <= 4000), CONSTRAINT training_sessions_times_valid CHECK (starts_at < ends_at), CONSTRAINT training_sessions_status_valid CHECK (status IN ('ACTIVE', 'CANCELLED')), CONSTRAINT training_sessions_cancellation_reason_valid CHECK (cancellation_reason IS NULL OR (cancellation_reason = btrim(cancellation_reason) AND char_length(cancellation_reason) BETWEEN 2 AND 500)), CONSTRAINT training_sessions_cancellation_complete CHECK ((status = 'ACTIVE' AND cancelled_at IS NULL AND cancelled_by_id IS NULL AND cancellation_reason IS NULL) OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND cancelled_by_id IS NOT NULL AND cancellation_reason IS NOT NULL))); CREATE INDEX training_sessions_plan_starts_idx ON training_sessions (plan_id, starts_at); CREATE INDEX training_sessions_status_starts_idx ON training_sessions (status, starts_at);
CREATE TYPE training_outcome_status AS ENUM ('COMPLETED', 'MISSED', 'REPLACED');
CREATE TABLE training_session_outcomes (session_id uuid NOT NULL REFERENCES training_sessions(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, status training_outcome_status NOT NULL, replacement_session_id uuid NULL REFERENCES training_sessions(id) ON DELETE RESTRICT, replacement_reason varchar(300) NULL, distance_metres integer NULL, reported_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (session_id, user_id), CONSTRAINT training_outcomes_replacement_valid CHECK ((status = 'REPLACED' AND replacement_session_id IS NOT NULL AND replacement_session_id <> session_id AND replacement_reason = btrim(replacement_reason) AND char_length(replacement_reason) BETWEEN 2 AND 300) OR (status IN ('COMPLETED', 'MISSED') AND replacement_session_id IS NULL AND replacement_reason IS NULL)), CONSTRAINT training_outcomes_distance_valid CHECK (distance_metres IS NULL OR (status = 'COMPLETED' AND distance_metres BETWEEN 1 AND 200000))); CREATE INDEX training_outcomes_user_idx ON training_session_outcomes (user_id, updated_at DESC); CREATE INDEX training_outcomes_leaderboard_idx ON training_session_outcomes (user_id, session_id) INCLUDE (distance_metres) WHERE status = 'COMPLETED' AND distance_metres IS NOT NULL;
CREATE TABLE competition_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title varchar(180) NOT NULL, url text NOT NULL, source varchar(180) NOT NULL, reviewed_on date NOT NULL, event_id uuid NULL REFERENCES events(id) ON DELETE CASCADE, modality_id uuid NULL REFERENCES modalities(id) ON DELETE RESTRICT, programme_id uuid NULL REFERENCES programmes(id) ON DELETE RESTRICT, team_id uuid NULL REFERENCES teams(id) ON DELETE RESTRICT, author_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, published_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT competition_documents_title_valid CHECK (title = btrim(title) AND char_length(title) BETWEEN 2 AND 180), CONSTRAINT competition_documents_url_valid CHECK (url ~ '^https://'), CONSTRAINT competition_documents_source_valid CHECK (source = btrim(source) AND char_length(source) BETWEEN 2 AND 180), CONSTRAINT competition_documents_context_valid CHECK (event_id IS NOT NULL OR modality_id IS NOT NULL), CONSTRAINT competition_documents_scope_valid CHECK (programme_id IS NOT NULL OR team_id IS NOT NULL OR event_id IS NOT NULL), CONSTRAINT competition_documents_modality_scope_valid CHECK (modality_id IS NULL OR programme_id IS NOT NULL OR team_id IS NOT NULL)); CREATE INDEX competition_documents_event_idx ON competition_documents (event_id, published_at DESC) WHERE event_id IS NOT NULL; CREATE INDEX competition_documents_modality_idx ON competition_documents (modality_id, published_at DESC) WHERE modality_id IS NOT NULL;
CREATE TYPE staff_capability AS ENUM ('COACH', 'MODERATOR');
CREATE TABLE staff_grants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, capability staff_capability NOT NULL, programme_id uuid NULL REFERENCES programmes(id) ON DELETE RESTRICT, team_id uuid NULL REFERENCES teams(id) ON DELETE RESTRICT, granted_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, granted_at timestamptz NOT NULL DEFAULT now(), revoked_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, revoked_at timestamptz NULL, revoke_reason varchar(500) NULL, CONSTRAINT staff_grants_scope_valid CHECK ((capability = 'COACH' AND (programme_id IS NOT NULL OR team_id IS NOT NULL)) OR (capability = 'MODERATOR' AND programme_id IS NULL AND team_id IS NULL)), CONSTRAINT staff_grants_revocation_valid CHECK ((revoked_at IS NULL AND revoked_by_id IS NULL AND revoke_reason IS NULL) OR (revoked_at IS NOT NULL AND revoked_by_id IS NOT NULL AND revoke_reason = btrim(revoke_reason) AND char_length(revoke_reason) BETWEEN 1 AND 500)));
CREATE UNIQUE INDEX staff_grants_active_scope_uidx ON staff_grants (user_id, capability, COALESCE(programme_id, '00000000-0000-0000-0000-000000000000'::uuid), COALESCE(team_id, '00000000-0000-0000-0000-000000000000'::uuid)) WHERE revoked_at IS NULL; CREATE INDEX staff_grants_active_user_idx ON staff_grants (user_id) WHERE revoked_at IS NULL;
CREATE FUNCTION reject_dependent_privileges() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS (SELECT 1 FROM users WHERE id = NEW.user_id AND is_dependent) THEN RAISE EXCEPTION 'dependants cannot receive platform or staff privileges'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER user_platform_roles_reject_dependant BEFORE INSERT OR UPDATE OF user_id ON user_platform_roles FOR EACH ROW EXECUTE FUNCTION reject_dependent_privileges(); CREATE TRIGGER staff_grants_reject_dependant BEFORE INSERT OR UPDATE OF user_id ON staff_grants FOR EACH ROW EXECUTE FUNCTION reject_dependent_privileges();
CREATE TABLE staff_grant_audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), staff_grant_id uuid NOT NULL REFERENCES staff_grants(id) ON DELETE RESTRICT, action varchar(20) NOT NULL, actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, occurred_at timestamptz NOT NULL DEFAULT now(), reason varchar(500) NULL, CONSTRAINT staff_grant_audit_events_action_valid CHECK (action IN ('GRANTED', 'REVOKED')), CONSTRAINT staff_grant_audit_events_reason_valid CHECK (reason IS NULL OR (reason = btrim(reason) AND char_length(reason) BETWEEN 1 AND 500))); CREATE INDEX staff_grant_audit_events_grant_idx ON staff_grant_audit_events (staff_grant_id, occurred_at);
CREATE FUNCTION audit_staff_grant_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP = 'INSERT' THEN INSERT INTO staff_grant_audit_events (staff_grant_id, action, actor_user_id) VALUES (NEW.id, 'GRANTED', NEW.granted_by_id); RETURN NEW; END IF; IF OLD.user_id <> NEW.user_id OR OLD.capability <> NEW.capability OR OLD.programme_id IS DISTINCT FROM NEW.programme_id OR OLD.team_id IS DISTINCT FROM NEW.team_id OR OLD.granted_by_id <> NEW.granted_by_id OR OLD.granted_at <> NEW.granted_at OR OLD.revoked_at IS NOT NULL OR NEW.revoked_at IS NULL THEN RAISE EXCEPTION 'staff grants are immutable except for one revocation'; END IF; INSERT INTO staff_grant_audit_events (staff_grant_id, action, actor_user_id, occurred_at, reason) VALUES (NEW.id, 'REVOKED', NEW.revoked_by_id, NEW.revoked_at, NEW.revoke_reason); RETURN NEW; END; $$;
CREATE TRIGGER staff_grants_audit_trigger AFTER INSERT OR UPDATE ON staff_grants FOR EACH ROW EXECUTE FUNCTION audit_staff_grant_change();
CREATE FUNCTION prevent_staff_grant_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'staff grant audit events are append-only'; END; $$;
CREATE TRIGGER staff_grant_audit_events_immutable_trigger BEFORE UPDATE OR DELETE ON staff_grant_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_staff_grant_audit_mutation();
CREATE TABLE event_team_audiences (event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE, team_id uuid NOT NULL REFERENCES teams(id) ON DELETE RESTRICT, PRIMARY KEY (event_id, team_id)); CREATE INDEX event_team_audiences_team_idx ON event_team_audiences (team_id, event_id);
CREATE TYPE photo_album_status AS ENUM ('OPEN', 'ARCHIVED');
CREATE TABLE photo_albums (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title varchar(180) NOT NULL, description varchar(2000) NOT NULL DEFAULT '', status photo_album_status NOT NULL DEFAULT 'OPEN', created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, archived_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, archived_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT photo_albums_title_valid CHECK (title = btrim(title) AND char_length(title) BETWEEN 2 AND 180), CONSTRAINT photo_albums_description_valid CHECK (description = btrim(description) AND char_length(description) <= 2000), CONSTRAINT photo_albums_lifecycle_valid CHECK ((status = 'OPEN' AND archived_by_id IS NULL AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_by_id IS NOT NULL AND archived_at IS NOT NULL))); CREATE INDEX photo_albums_status_created_idx ON photo_albums (status, created_at DESC, id DESC);
CREATE TABLE photo_album_programme_audiences (album_id uuid NOT NULL REFERENCES photo_albums(id) ON DELETE CASCADE, programme_id uuid NOT NULL REFERENCES programmes(id) ON DELETE RESTRICT, PRIMARY KEY (album_id, programme_id)); CREATE INDEX photo_album_programme_audiences_lookup_idx ON photo_album_programme_audiences (programme_id, album_id);
CREATE TABLE photo_album_team_audiences (album_id uuid NOT NULL REFERENCES photo_albums(id) ON DELETE CASCADE, team_id uuid NOT NULL REFERENCES teams(id) ON DELETE RESTRICT, PRIMARY KEY (album_id, team_id)); CREATE INDEX photo_album_team_audiences_lookup_idx ON photo_album_team_audiences (team_id, album_id);
CREATE FUNCTION ensure_photo_album_has_audience() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE target_album_id uuid; BEGIN IF TG_TABLE_NAME = 'photo_albums' THEN target_album_id := NEW.id; ELSE target_album_id := OLD.album_id; END IF; IF EXISTS (SELECT 1 FROM photo_albums WHERE id = target_album_id) AND NOT EXISTS (SELECT 1 FROM photo_album_programme_audiences WHERE album_id = target_album_id) AND NOT EXISTS (SELECT 1 FROM photo_album_team_audiences WHERE album_id = target_album_id) THEN RAISE EXCEPTION 'photo album requires an audience'; END IF; IF TG_OP = 'DELETE' THEN RETURN OLD; END IF; RETURN NEW; END; $$;
CREATE CONSTRAINT TRIGGER photo_albums_audience_required_trigger AFTER INSERT OR UPDATE ON photo_albums DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ensure_photo_album_has_audience();
CREATE CONSTRAINT TRIGGER photo_album_programme_audience_required_trigger AFTER DELETE ON photo_album_programme_audiences DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ensure_photo_album_has_audience();
CREATE CONSTRAINT TRIGGER photo_album_team_audience_required_trigger AFTER DELETE ON photo_album_team_audiences DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ensure_photo_album_has_audience();
CREATE TABLE photo_album_audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), album_id uuid NOT NULL REFERENCES photo_albums(id) ON DELETE RESTRICT, action varchar(20) NOT NULL CHECK (action IN ('CREATED', 'ARCHIVED')), actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, occurred_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX photo_album_audit_events_album_idx ON photo_album_audit_events (album_id, occurred_at, id);
CREATE FUNCTION audit_photo_album_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP = 'INSERT' THEN INSERT INTO photo_album_audit_events (album_id, action, actor_user_id, occurred_at) VALUES (NEW.id, 'CREATED', NEW.created_by_id, NEW.created_at); RETURN NEW; END IF; IF OLD.status = 'OPEN' AND NEW.status = 'ARCHIVED' AND NEW.archived_by_id IS NOT NULL AND NEW.archived_at IS NOT NULL THEN INSERT INTO photo_album_audit_events (album_id, action, actor_user_id, occurred_at) VALUES (NEW.id, 'ARCHIVED', NEW.archived_by_id, NEW.archived_at); RETURN NEW; END IF; RAISE EXCEPTION 'photo album lifecycle transition is invalid'; END; $$;
CREATE TRIGGER photo_albums_audit_trigger AFTER INSERT OR UPDATE OF status ON photo_albums FOR EACH ROW EXECUTE FUNCTION audit_photo_album_change();
CREATE FUNCTION prevent_photo_album_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'photo album audit events are append-only'; END; $$;
CREATE TRIGGER photo_album_audit_events_immutable_trigger BEFORE UPDATE OR DELETE ON photo_album_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_photo_album_audit_mutation();
CREATE TYPE announcement_status AS ENUM ('DRAFT', 'PUBLISHED', 'EXPIRED'); CREATE TYPE announcement_target_type AS ENUM ('PROGRAMME', 'TEAM', 'CATEGORY', 'MODALITY', 'EVENT', 'GUARDIAN');
CREATE TABLE announcements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title varchar(180) NOT NULL, body varchar(4000) NOT NULL, status announcement_status NOT NULL DEFAULT 'DRAFT', author_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, published_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, expired_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, published_at timestamptz NULL, expires_at timestamptz NULL, expired_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT announcements_title_valid CHECK (title = btrim(title) AND char_length(title) BETWEEN 2 AND 180), CONSTRAINT announcements_body_valid CHECK (body = btrim(body) AND char_length(body) BETWEEN 2 AND 4000), CONSTRAINT announcements_status_valid CHECK ((status = 'DRAFT' AND published_at IS NULL AND published_by_id IS NULL AND expired_at IS NULL AND expired_by_id IS NULL) OR (status = 'PUBLISHED' AND published_at IS NOT NULL AND published_by_id IS NOT NULL AND expired_at IS NULL AND expired_by_id IS NULL) OR (status = 'EXPIRED' AND published_at IS NOT NULL AND published_by_id IS NOT NULL AND expired_at IS NOT NULL AND expired_by_id IS NOT NULL)), CONSTRAINT announcements_expiry_valid CHECK (expires_at IS NULL OR published_at IS NULL OR expires_at > published_at)); CREATE INDEX announcements_visible_idx ON announcements (status, published_at DESC, expires_at);
CREATE TABLE announcement_targets (announcement_id uuid NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, target_type announcement_target_type NOT NULL, target_id uuid NULL, CONSTRAINT announcement_targets_shape_valid CHECK ((target_type = 'GUARDIAN' AND target_id IS NULL) OR (target_type <> 'GUARDIAN' AND target_id IS NOT NULL))); CREATE UNIQUE INDEX announcement_targets_unique_idx ON announcement_targets (announcement_id, target_type, target_id) NULLS NOT DISTINCT; CREATE INDEX announcement_targets_lookup_idx ON announcement_targets (target_type, target_id, announcement_id);
CREATE TABLE announcement_deliveries (announcement_id uuid NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, delivered_at timestamptz NOT NULL DEFAULT now(), read_at timestamptz NULL, PRIMARY KEY (announcement_id, user_id)); CREATE INDEX announcement_deliveries_user_idx ON announcement_deliveries (user_id, read_at, delivered_at DESC);
CREATE TABLE announcement_audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), announcement_id uuid NOT NULL REFERENCES announcements(id) ON DELETE RESTRICT, action varchar(20) NOT NULL, actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, occurred_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT announcement_audit_action_valid CHECK (action IN ('AUTHORED', 'PUBLISHED', 'EXPIRED'))); CREATE INDEX announcement_audit_events_announcement_idx ON announcement_audit_events (announcement_id, occurred_at);
CREATE TABLE whatsapp_group_targets (whatsapp_group_id uuid NOT NULL REFERENCES whatsapp_groups(id) ON DELETE CASCADE, target_type announcement_target_type NOT NULL, target_id uuid NULL, CONSTRAINT whatsapp_group_targets_shape_valid CHECK ((target_type = 'GUARDIAN' AND target_id IS NULL) OR (target_type <> 'GUARDIAN' AND target_id IS NOT NULL))); CREATE UNIQUE INDEX whatsapp_group_targets_unique_idx ON whatsapp_group_targets (whatsapp_group_id, target_type, target_id) NULLS NOT DISTINCT; CREATE INDEX whatsapp_group_targets_lookup_idx ON whatsapp_group_targets (target_type, target_id, whatsapp_group_id);
INSERT INTO whatsapp_group_targets (whatsapp_group_id, target_type, target_id) SELECT id, 'PROGRAMME', programme_id FROM whatsapp_groups WHERE programme_id IS NOT NULL;
CREATE FUNCTION audit_announcement_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP = 'INSERT' THEN INSERT INTO announcement_audit_events (announcement_id, action, actor_user_id) VALUES (NEW.id, 'AUTHORED', NEW.author_id); ELSIF OLD.status = 'DRAFT' AND NEW.status = 'PUBLISHED' THEN INSERT INTO announcement_audit_events (announcement_id, action, actor_user_id) VALUES (NEW.id, 'PUBLISHED', NEW.published_by_id); ELSIF OLD.status = 'PUBLISHED' AND NEW.status = 'EXPIRED' THEN INSERT INTO announcement_audit_events (announcement_id, action, actor_user_id) VALUES (NEW.id, 'EXPIRED', NEW.expired_by_id); ELSE RAISE EXCEPTION 'announcements may only be authored, published, or expired'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER announcements_audit_trigger AFTER INSERT OR UPDATE ON announcements FOR EACH ROW EXECUTE FUNCTION audit_announcement_change();

CREATE TABLE activity_connections (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider varchar(40) NOT NULL, provider_user_id varchar(255) NOT NULL, status varchar(40) NOT NULL DEFAULT 'ACTIVE', credentials_ciphertext bytea NULL, credential_key_id varchar(120) NULL, credential_expires_at timestamptz NULL, credential_version bigint NOT NULL DEFAULT 1, scopes text[] NOT NULL DEFAULT '{}', sync_cursor text NULL, last_successful_sync_at timestamptz NULL, last_error_code varchar(120) NULL, last_error_message varchar(2000) NULL, last_error_at timestamptz NULL, disconnected_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT activity_connections_provider_valid CHECK (provider = btrim(provider) AND provider ~ '^[a-z][a-z0-9_-]{1,39}$'),
 CONSTRAINT activity_connections_provider_user_valid CHECK (provider_user_id = btrim(provider_user_id) AND char_length(provider_user_id) BETWEEN 1 AND 255),
 CONSTRAINT activity_connections_status_valid CHECK (status IN ('ACTIVE', 'REAUTHORIZATION_REQUIRED', 'DISCONNECTED')),
 CONSTRAINT activity_connections_credentials_valid CHECK ((status = 'DISCONNECTED' AND credentials_ciphertext IS NULL AND credential_key_id IS NULL AND disconnected_at IS NOT NULL) OR (status <> 'DISCONNECTED' AND credentials_ciphertext IS NOT NULL AND octet_length(credentials_ciphertext) > 0 AND credential_key_id IS NOT NULL AND credential_key_id = btrim(credential_key_id) AND char_length(credential_key_id) BETWEEN 1 AND 120 AND disconnected_at IS NULL)),
 CONSTRAINT activity_connections_credential_version_valid CHECK (credential_version > 0),
 CONSTRAINT activity_connections_scopes_valid CHECK (array_position(scopes, NULL) IS NULL),
 CONSTRAINT activity_connections_error_valid CHECK ((last_error_code IS NULL AND last_error_message IS NULL AND last_error_at IS NULL) OR (last_error_code IS NOT NULL AND last_error_code = btrim(last_error_code) AND char_length(last_error_code) BETWEEN 1 AND 120 AND last_error_message IS NOT NULL AND char_length(last_error_message) BETWEEN 1 AND 2000 AND last_error_at IS NOT NULL)),
 CONSTRAINT activity_connections_user_provider_unique UNIQUE (user_id, provider),
 CONSTRAINT activity_connections_provider_identity_unique UNIQUE (provider, provider_user_id),
 CONSTRAINT activity_connections_identity_unique UNIQUE (id, user_id, provider)
);
CREATE INDEX activity_connections_sync_idx ON activity_connections (status, last_successful_sync_at) WHERE status <> 'DISCONNECTED';

CREATE TABLE activity_sync_jobs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), idempotency_key uuid NOT NULL UNIQUE, connection_id uuid NOT NULL REFERENCES activity_connections(id) ON DELETE CASCADE, reason varchar(20) NOT NULL, status varchar(20) NOT NULL DEFAULT 'PENDING', attempts integer NOT NULL DEFAULT 0, checkpoint text NULL, last_error_code varchar(120) NULL, last_error_message varchar(2000) NULL, requested_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz NULL, finished_at timestamptz NULL, updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT activity_sync_jobs_reason_valid CHECK (reason IN ('LOGIN', 'WEBHOOK', 'MANUAL', 'BACKFILL', 'RECONCILIATION')),
 CONSTRAINT activity_sync_jobs_status_valid CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
 CONSTRAINT activity_sync_jobs_attempts_valid CHECK (attempts >= 0),
 CONSTRAINT activity_sync_jobs_lifecycle_valid CHECK ((status = 'PENDING' AND started_at IS NULL AND finished_at IS NULL) OR (status = 'RUNNING' AND started_at IS NOT NULL AND finished_at IS NULL) OR (status IN ('SUCCEEDED', 'FAILED', 'CANCELLED') AND finished_at IS NOT NULL)),
 CONSTRAINT activity_sync_jobs_error_valid CHECK ((last_error_code IS NULL AND last_error_message IS NULL) OR (last_error_code IS NOT NULL AND last_error_code = btrim(last_error_code) AND char_length(last_error_code) BETWEEN 1 AND 120 AND last_error_message IS NOT NULL AND char_length(last_error_message) BETWEEN 1 AND 2000))
);
CREATE INDEX activity_sync_jobs_pending_idx ON activity_sync_jobs (requested_at, id) WHERE status = 'PENDING';
CREATE INDEX activity_sync_jobs_connection_idx ON activity_sync_jobs (connection_id, requested_at DESC, id DESC);

CREATE TABLE synced_activities (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), connection_id uuid NOT NULL, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider varchar(40) NOT NULL, provider_activity_id varchar(255) NOT NULL, provider_updated_at timestamptz NULL, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, sport varchar(120) NOT NULL, normalized_sport varchar(80) NOT NULL, duration_seconds integer NOT NULL, moving_duration_seconds integer NULL, distance_metres double precision NULL, average_heart_rate smallint NULL, maximum_heart_rate smallint NULL, provider_metrics jsonb NOT NULL DEFAULT '{}', raw_summary jsonb NOT NULL DEFAULT '{}', payload_sha256 bytea NOT NULL, normalization_version integer NOT NULL DEFAULT 1, deleted_at timestamptz NULL, ingested_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT synced_activities_connection_fk FOREIGN KEY (connection_id, user_id, provider) REFERENCES activity_connections(id, user_id, provider) ON DELETE CASCADE,
 CONSTRAINT synced_activities_provider_activity_valid CHECK (provider_activity_id = btrim(provider_activity_id) AND char_length(provider_activity_id) BETWEEN 1 AND 255),
 CONSTRAINT synced_activities_sport_valid CHECK (sport = btrim(sport) AND char_length(sport) BETWEEN 1 AND 120 AND normalized_sport = btrim(normalized_sport) AND char_length(normalized_sport) BETWEEN 1 AND 80),
 CONSTRAINT synced_activities_times_valid CHECK (starts_at < ends_at),
 CONSTRAINT synced_activities_duration_valid CHECK (duration_seconds > 0 AND (moving_duration_seconds IS NULL OR moving_duration_seconds >= 0)),
 CONSTRAINT synced_activities_distance_valid CHECK (distance_metres IS NULL OR distance_metres >= 0),
 CONSTRAINT synced_activities_heart_rate_valid CHECK ((average_heart_rate IS NULL OR average_heart_rate BETWEEN 20 AND 260) AND (maximum_heart_rate IS NULL OR maximum_heart_rate BETWEEN 20 AND 260) AND (average_heart_rate IS NULL OR maximum_heart_rate IS NULL OR average_heart_rate <= maximum_heart_rate)),
 CONSTRAINT synced_activities_payload_hash_valid CHECK (octet_length(payload_sha256) = 32),
 CONSTRAINT synced_activities_normalization_version_valid CHECK (normalization_version > 0),
 CONSTRAINT synced_activities_provider_identity_unique UNIQUE (provider, provider_activity_id),
 CONSTRAINT synced_activities_user_identity_unique UNIQUE (id, user_id)
);
CREATE INDEX synced_activities_user_starts_idx ON synced_activities (user_id, starts_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX synced_activities_connection_updated_idx ON synced_activities (connection_id, updated_at DESC, id DESC);

CREATE TABLE training_session_activity_matches (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES training_sessions(id) ON DELETE CASCADE, activity_id uuid NOT NULL, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, status varchar(20) NOT NULL DEFAULT 'SUGGESTED', confidence smallint NOT NULL, match_basis jsonb NOT NULL DEFAULT '{}', decided_by_user_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT, decided_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT training_session_activity_matches_activity_fk FOREIGN KEY (activity_id, user_id) REFERENCES synced_activities(id, user_id) ON DELETE CASCADE,
 CONSTRAINT training_session_activity_matches_status_valid CHECK (status IN ('SUGGESTED', 'CONFIRMED', 'REJECTED')),
 CONSTRAINT training_session_activity_matches_confidence_valid CHECK (confidence BETWEEN 0 AND 100),
 CONSTRAINT training_session_activity_matches_decision_valid CHECK ((status = 'SUGGESTED' AND decided_by_user_id IS NULL AND decided_at IS NULL) OR (status IN ('CONFIRMED', 'REJECTED') AND decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)),
 CONSTRAINT training_session_activity_matches_unique UNIQUE (session_id, activity_id, user_id)
);
CREATE INDEX training_session_activity_matches_user_idx ON training_session_activity_matches (user_id, status, updated_at DESC, id DESC);
CREATE UNIQUE INDEX training_session_activity_matches_confirmed_session_uidx ON training_session_activity_matches (session_id, user_id) WHERE status = 'CONFIRMED';
CREATE UNIQUE INDEX training_session_activity_matches_confirmed_activity_uidx ON training_session_activity_matches (activity_id) WHERE status = 'CONFIRMED';

CREATE TYPE feature_availability_mode AS ENUM ('DISABLED', 'ADMIN_ONLY', 'ENABLED');
CREATE TABLE feature_flags (
 feature_key varchar(80) PRIMARY KEY,
 mode feature_availability_mode NOT NULL,
 updated_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT,
 updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT feature_flags_key_valid CHECK (feature_key = btrim(feature_key) AND feature_key ~ '^[a-z][a-z0-9_]{1,79}$')
);
INSERT INTO feature_flags (feature_key, mode) VALUES ('suggestions', 'ENABLED'), ('photo_submissions', 'DISABLED');
CREATE TABLE feature_flag_events (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 feature_key varchar(80) NOT NULL REFERENCES feature_flags(feature_key) ON DELETE RESTRICT,
 previous_mode feature_availability_mode NOT NULL,
 new_mode feature_availability_mode NOT NULL,
 actor_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 occurred_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT feature_flag_events_change_valid CHECK (previous_mode <> new_mode)
);
CREATE INDEX feature_flag_events_feature_idx ON feature_flag_events (feature_key, occurred_at DESC, id DESC);
CREATE FUNCTION audit_feature_flag_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.updated_by_id IS NULL THEN RAISE EXCEPTION 'feature flag changes require an administrator'; END IF; IF OLD.mode = NEW.mode THEN RETURN NEW; END IF; INSERT INTO feature_flag_events (feature_key, previous_mode, new_mode, actor_user_id, occurred_at) VALUES (NEW.feature_key, OLD.mode, NEW.mode, NEW.updated_by_id, NEW.updated_at); RETURN NEW; END; $$;
CREATE TRIGGER feature_flags_audit_trigger AFTER UPDATE ON feature_flags FOR EACH ROW EXECUTE FUNCTION audit_feature_flag_change();
CREATE FUNCTION prevent_feature_flag_event_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'feature flag events are append-only'; END; $$;
CREATE TRIGGER feature_flag_events_immutable_trigger BEFORE UPDATE OR DELETE ON feature_flag_events FOR EACH ROW EXECUTE FUNCTION prevent_feature_flag_event_mutation();

CREATE TYPE suggestion_category AS ENUM ('FACILITIES', 'EQUIPMENT', 'TRAINING', 'EVENTS', 'COMMUNICATION', 'OTHER');
CREATE TYPE suggestion_status AS ENUM ('SUBMITTED', 'UNDER_REVIEW', 'PLANNED', 'DECLINED', 'COMPLETED');
CREATE TABLE suggestions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 requester_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 category suggestion_category NOT NULL,
 subject varchar(160) NOT NULL,
 description varchar(3000) NOT NULL,
 status suggestion_status NOT NULL DEFAULT 'SUBMITTED',
 staff_response varchar(2000) NULL,
 responded_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT,
 responded_at timestamptz NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT suggestions_subject_valid CHECK (subject = btrim(subject) AND char_length(subject) BETWEEN 3 AND 160),
 CONSTRAINT suggestions_description_valid CHECK (description = btrim(description) AND char_length(description) BETWEEN 10 AND 3000),
 CONSTRAINT suggestions_response_valid CHECK (staff_response IS NULL OR (staff_response = btrim(staff_response) AND char_length(staff_response) BETWEEN 2 AND 2000)),
 CONSTRAINT suggestions_response_actor_valid CHECK ((staff_response IS NULL AND responded_by_id IS NULL AND responded_at IS NULL) OR (staff_response IS NOT NULL AND responded_by_id IS NOT NULL AND responded_at IS NOT NULL)),
 CONSTRAINT suggestions_terminal_response_valid CHECK (status NOT IN ('DECLINED', 'COMPLETED') OR staff_response IS NOT NULL)
);
CREATE INDEX suggestions_requester_created_idx ON suggestions (requester_id, created_at DESC, id DESC);
CREATE INDEX suggestions_triage_idx ON suggestions (status, updated_at DESC, id DESC);
