//go:build integration

package main

import (
	"bytes"
	"context"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/cfcoimbra/mycfc/internal/db"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

func TestGeneratedApprovalIsAcceptedByDatabaseCanonicalBoundary(t *testing.T) {
	databaseURL := strings.TrimSpace(os.Getenv("TEST_DATABASE_URL"))
	if databaseURL == "" {
		t.Skip("TEST_DATABASE_URL required")
	}
	ctx := context.Background()
	connection, err := pgx.Connect(ctx, databaseURL)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = connection.Close(context.Background()) })
	tx, err := connection.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = tx.Rollback(context.Background()) })

	for _, statement := range []string{
		`CREATE SCHEMA IF NOT EXISTS mycfc_meta`,
		`CREATE TABLE IF NOT EXISTS mycfc_meta.schema_migrations(version text PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now())`,
		`UPDATE guardian_authority_relationships SET state='EXPIRED',conflict=false,conflict_actor_ref=NULL WHERE state IN('VERIFIED','SUSPENDED')`,
		`UPDATE guardian_application_intake_release SET enabled=false,policy_version=NULL,policy_sha256=NULL,approval_sha256=NULL,
			image_digest=NULL,schema_migration_digest=NULL,enabled_by=NULL,enabled_at=NULL WHERE singleton`,
		`UPDATE guardian_authority_policies SET enabled=false,enabled_at=NULL,enabled_by=NULL WHERE enabled`,
		`DELETE FROM sessions session USING users subject WHERE session.user_id=subject.id AND session.subject_indexed AND subject.is_dependent`,
		`UPDATE users SET minor_login_id=NULL,password_hash=NULL WHERE is_dependent`,
	} {
		if _, err = tx.Exec(ctx, statement); err != nil {
			t.Fatal(err)
		}
	}
	for _, version := range db.EmbeddedMigrationInventory() {
		if _, err = tx.Exec(ctx, `INSERT INTO mycfc_meta.schema_migrations(version) VALUES($1) ON CONFLICT DO NOTHING`, version); err != nil {
			t.Fatal(err)
		}
	}

	actor := uuid.New()
	if _, err = tx.Exec(ctx, `INSERT INTO users(id,name,email,password_hash,email_verified_at,date_of_birth)
		VALUES($1,'Generated approval administrator',$2,'hash',clock_timestamp(),'1990-01-01')`,
		actor, "generated-approval-"+uuid.NewString()+"@example.test"); err != nil {
		t.Fatal(err)
	}
	if _, err = tx.Exec(ctx, `INSERT INTO user_platform_roles(user_id,role_id) SELECT $1,id FROM platform_roles WHERE code='ADMIN'`, actor); err != nil {
		t.Fatal(err)
	}
	databaseName := connection.Config().Database
	imageDigest := "sha256:" + strings.Repeat("d", 64)
	if _, err = tx.Exec(ctx, `UPDATE guardian_ops.runtime_release_binding
		SET database_name=$1,image_digest=$2,schema_migration_digest=$3,generation=generation+1,bound_at=clock_timestamp()
		WHERE singleton`, databaseName, imageDigest, db.EmbeddedMigrationDigest()); err != nil {
		t.Fatal(err)
	}

	location, err := time.LoadLocation("Europe/Lisbon")
	if err != nil {
		t.Fatal(err)
	}
	today := time.Now().In(location)
	date := today.Format(time.DateOnly)
	args := []string{
		"--actor-ref", actor.String(),
		"--expected-database", databaseName,
		"--policy-version", "guardian-v2-generated-" + strings.ReplaceAll(uuid.NewString(), "-", "")[:12],
		"--controller-approval-reference", "direcao/minute/&/reference",
		"--controller-approved-on", date,
		"--effective-on", date,
		"--review-due-on", today.AddDate(1, 0, 0).Format(time.DateOnly),
		"--legal-reviewer-reference", "legal/reviewer/reference",
		"--legal-review-reference", "legal/review/&/evidence",
		"--legal-reviewed-on", date,
	}
	var generated bytes.Buffer
	if err = generateApproval(args, &generated); err != nil {
		t.Fatal(err)
	}
	if bytes.HasSuffix(generated.Bytes(), []byte{'\n'}) {
		t.Fatal("generator added a trailing newline")
	}
	canonical, policy, err := parseApproval(generated.Bytes(), actor, databaseName)
	if err != nil {
		t.Fatal(err)
	}

	var ready, already bool
	var version string
	var policyHash, approvalHash []byte
	var relationships, credentials, sessions int64
	if err = tx.QueryRow(ctx, `SELECT * FROM guardian_ops.preflight($1,$2,$3,$4,$5,$6,$7)`,
		actor, string(canonical), canonical, policy, imageDigest, db.EmbeddedMigrationDigest(), databaseName).
		Scan(&ready, &already, &version, &policyHash, &approvalHash, &relationships, &credentials, &sessions); err != nil {
		t.Fatalf("database rejected generated canonical approval: %v", err)
	}
	if !ready || already || relationships != 0 || credentials != 0 || sessions != 0 {
		t.Fatalf("ready=%t already=%t relationships=%d credentials=%d sessions=%d", ready, already, relationships, credentials, sessions)
	}
}
